baseURL: "https://daliego.github.io"
title: Diego de Sousa Araújo
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    - name: Publications
      url: publications/
      weight: 2
    - name: Professional Projects
      url: professional-work/
      weight: 3
    - name: Study Cases
      url: personal-work/
      weight: 4
    - name: Certifications
      url: certifications/
      weight: 5

params:
  description: "Web Developer with 3+ years of experience building responsive, production-ready web applications using Next.js, Vue.js, and React. Strong full-stack background with Nest.js and Django. Experience with containerization and deployment pipelines. Also skilled in mobile development (React Native). Known for fast adaptation, collaboration in agile teams and continuous learning."
  author: Diego de Sousa Araújo
  # googleAnalyticsID: "G-XXXXX"
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["books", "courses", "publications", "data"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Diego de Sousa Araújo
    subtitle: "Web Developer with 3+ years of experience building responsive, production-ready web applications using Next.js, Vue.js, and React. Strong full-stack background with Nest.js and Django. Experience with containerization and deployment pipelines. Also skilled in mobile development (React Native). Known for fast adaptation, collaboration in agile teams and continuous learning."
    imageUrl: "picture.png"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: Professional Projects
        url: professional-work/
      - name: Personal Work / Study Cases
        url: personal-work/
      - name: Publications
        url: publications/
      - name: Certifications / Awards
        url: certifications/
      - name: Tags
        url: tags/
      - name: Website
        url: https://diego-dev-frontend.my.canva.site/

  socialIcons:
    - name: CV
      url: https://www.canva.com/design/DAG9mT40Co0/_6oX6owRfzajPQw3jkmoow/edit?utm_content=DAG9mT40Co0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
    - name: Website
      url: https://diego-dev-frontend.my.canva.site/
    - name: GitHub
      url: https://github.com/Daliego
    - name: LinkedIn
      url: https://www.linkedin.com/in/daliego/
    - name: Email
      url: mailto:diesgo.araujo@gmail.com
    - name: University
      url: https://www.ifpi.edu.br/

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "Diego de Sousa Araújo"
    icon: application_logo.png
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
